services:
  - type: web
    name: codehunt-2026-theme2
    runtime: node
    region: singapore
    plan: free
    rootDir: .
    buildCommand: npm install && npm run build && cd backend && npm install
    startCommand: node backend/server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: FIREBASE_CREDENTIALS
        sync: false   # Set this manually in Render dashboard
